### ISSUE TITLE
Error messages differing by country

### ISSUE THREAD

**Issue by paullenz** [mysociety/oxfam-lookup#1]
Here are the differing error responses we were getting with the 2 countries initially set up. 

Thanks,
Carina
# 

When submitting an invalid postcode for the UK the json response returns with statuses of 400 (e.g. http://oxfam-api.mysociety.org/postcode/UK/2148) or 404 (e.g. http://oxfam-api.mysociety.org/postcode/UK/AL1%201AA). 
However, for AU a 500 error is returned (e.g. http://oxfam-api.mysociety.org/postcode/AU/AL1201AA)

**Comment by dracos** [comment]
The unknown AU postcodes should now return a 404 as with the UK.
